# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19yWA4DpJSqK8Nx4tzmOXD4df8PPSBRII
"""

import pandas as pd
import numpy as np

from tabulate import tabulate

import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

import random
data = [['robot', 1], 
        ['human', 0]]*10
random.shuffle(data)
col_names = ["whoAmI"]
print(tabulate(data, headers=col_names, tablefmt="fancy_grid", showindex="always"))