# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h89uysSeiE2gEDjfNUwVOU0_YFrPT03F
"""

import pandas as pd

df = pd.read_csv('/content/sample_data/california_housing_train.csv')

df.head(n=100)

df.loc[df['median_house_value'] > 500,'population']

df.loc[(df.median_house_value > 0) & (df.median_house_value < 500)]

min(df['households'])

max(df['households'])

min(df['population'])

max(df['population'])

df[df['population'] == df['population'].min()]['households'].max()

max(df[df['population'] == df['population'].min()]['households'])