# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19yWA4DpJSqK8Nx4tzmOXD4df8PPSBRII
"""

!pip --version

!pip install pandas

import pandas as pd

import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.get_dummies(lst ,columns={'WhoAmI'})
data.head()
data = pd.get_dummies(random.sample(['robot', 'human']*10, 10) ,columns={'WhoAmI'})
data.head()

import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame(lst ,columns={'WhoAmI'})
data.head()
data = pd.DataFrame(random.sample(['robot', 'human']*10, 10) ,columns={'WhoAmI'})
data.head()